# Generated by Django 4.0.1 on 2023-02-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customerregistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
